/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build a session from a track source
         * @description Resolves the source into a catalogue, runs the deterministic planner, evaluates the
         *     result and persists it.
         *
         *     Returns **422** when no valid session can be built from the catalogue — a playlist with
         *     no track slow enough to cool down on, for example. That is a refusal, not a failure:
         *     the engine will not return a session that skips its cooldown. The structured reasons
         *     are in `detail`.
         */
        post: operations["generateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List past sessions, newest first */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay one session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate a session */
        post: operations["submitFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quality/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * BPM resolution coverage per source
         * @description Rows of `mart_bpm_coverage` — one per BPM source (E.3).
         */
        get: operations["getQualityCoverage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quality/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalogue-wide data quality
         * @description A single aggregate record, as E.3 specifies. `mart_data_quality` itself has one row per
         *     `confidence_method`; that breakdown is returned inside `by_method`, so this endpoint and
         *     `/v1/quality/coverage` do not duplicate each other.
         */
        get: operations["getQualitySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            reasons?: string[];
        };
        /** @enum {string} */
        Level: "beginner" | "intermediate" | "advanced";
        /** @enum {string} */
        Goal: "endurance" | "intervals" | "recovery";
        /** @enum {string} */
        Zone: "Z1" | "Z2" | "Z3" | "Z4" | "Z5";
        /** @enum {string} */
        Verdict: "safe" | "review";
        /** @enum {string} */
        SegmentRole: "warmup" | "recovery" | "endurance" | "cardio" | "intensity" | "sprint" | "cooldown";
        TrackSource: {
            /** @enum {string} */
            type: "deezer_url" | "csv" | "demo";
            /**
             * @description Playlist URL, CSV path, or `""` for `demo` (which reads the committed catalogue).
             *     `deezer_url` needs live network and is refused with 422 under `DEMO_MODE` (E.8).
             */
            value: string;
        };
        GenerateSessionRequest: {
            source: components["schemas"]["TrackSource"];
            level: components["schemas"]["Level"];
            goal: components["schemas"]["Goal"];
            duration_min: number;
        };
        Track: {
            track_id: string;
            title: string;
            artist: string;
            duration_s: number;
            /** @description Normalized per E.2. Never null inside a segment. */
            bpm_effective?: number | null;
            zone?: components["schemas"]["Zone"] | null;
            /** @description E.2 — 0.9 cross-validated, 0.6 single source, 0.3 under review. */
            confidence?: number | null;
            preview_url?: string | null;
        };
        Coaching: {
            instruction: string;
            transition_cue: string;
            kb_refs: string[];
        };
        Segment: {
            order: number;
            track: components["schemas"]["Track"];
            zone: components["schemas"]["Zone"];
            /** @description Additive to E.3 — see ADR-007 and the header note. */
            role: components["schemas"]["SegmentRole"];
            /** @description The FULL track duration (ADR-007 decision 3). */
            duration_s: number;
            coaching?: components["schemas"]["Coaching"] | null;
        };
        ExcludedTrack: {
            track_id: string;
            /**
             * @description Stable code, not prose: `no_bpm`, `duplicate_track_id`, `invalid_duration`,
             *     `not_needed`, or `goal_<goal>_zone`.
             */
            reason: string;
        };
        SessionPlan: {
            session_id: string;
            level: components["schemas"]["Level"];
            goal: components["schemas"]["Goal"];
            duration_min: number;
            verdict: components["schemas"]["Verdict"];
            segments: components["schemas"]["Segment"][];
            excluded?: components["schemas"]["ExcludedTrack"][];
            /** @description Signed. Positive means the session overruns the target. */
            duration_gap_s: number;
            warnings: string[];
            /** Format: date-time */
            created_at: string;
        };
        SessionSummary: {
            session_id: string;
            level: components["schemas"]["Level"];
            goal: components["schemas"]["Goal"];
            duration_min: number;
            verdict: components["schemas"]["Verdict"];
            n_segments: number;
            duration_gap_s: number;
            /** Format: date-time */
            created_at: string;
        };
        SessionPage: {
            items: components["schemas"]["SessionSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
        FeedbackRequest: {
            /** @enum {string} */
            rating: "up" | "down";
            note?: string | null;
        };
        Feedback: {
            session_id: string;
            /** @enum {string} */
            rating: "up" | "down";
            note?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CoverageRow: {
            /** @description E.2 enum — `deezer`, `librosa`, `getsongbpm` or `manual`. */
            source: string;
            /** @description Tracks this source gave an opinion on. */
            n_tracks: number;
            /** @description A PERCENTAGE, 0-100 — not a 0-1 ratio. Computed as n_usable over the WHOLE catalogue, not over n_tracks, so the figures are comparable between sources. Stated here because the frontend reads this file and nothing else. */
            pct_of_catalogue: number;
            /** @description Of those, how many carried a usable BPM after E.2 normalization. */
            n_usable: number;
        };
        QualitySummary: {
            n_tracks: number;
            /** @description Planner-eligible tracks — E.2 excludes the rest. */
            n_with_bpm: number;
            /** @description A percentage, 0-100 — not a 0-1 ratio. */
            pct_with_bpm: number;
            n_flagged_review: number;
            /** @description A percentage, 0-100 — not a 0-1 ratio. */
            pct_flagged_review: number;
            avg_confidence?: number | null;
            /** @description Track count per `confidence_method` — the mart's own grain. */
            by_method: {
                [key: string]: number;
            };
        };
    };
    responses: {
        /** @description No such resource (RFC 7807). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request is well-formed but cannot be satisfied (RFC 7807). */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        SessionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    generateSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSessionRequest"];
            };
        };
        responses: {
            /** @description The generated session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPlan"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of session summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPlan"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    submitFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Feedback recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feedback"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getQualityCoverage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One record per resolution source. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageRow"][];
                };
            };
        };
    };
    getQualitySummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One aggregate record over the catalogue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualitySummary"];
                };
            };
        };
    };
}
